### ISSUE TITLE
Ignore pods that aren't healthy when calculating scale down

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#361]
I had a couple pods:
```
default        inflate-7bb86df7fb-sztk5                   0/1     Preempting   0          37m
default        inflate-7bb86df7fb-trmbb                   0/1     OutOfcpu     0          36m
```
Yet the instance never scaled down.

**Comment by JacobGabrielson** [comment]
@ellistarn any idea why the `OutOfCpu` happened? Is that because the pod spec didn't ask for enough?

**Comment by ellistarn** [comment]
I manually injected this error condition to simulate this case.

**Comment by njtran** [comment]
Should we do this for any pod with this status? 

```
  - lastProbeTime: null
    lastTransitionTime: "2021-05-05T19:22:45Z"
    status: "False"
    type: Ready
```

**Comment by njtran** [comment]
Additionally
```
    - lastProbeTime: null
      lastTransitionTime: "2021-05-05T19:22:39Z"
      status: "True"
      type: Initialized
```

**Comment by ellistarn** [comment]
Report
```
➜  karpenter git:(outofcpu) ✗ k get pods
NAME                       READY   STATUS              RESTARTS   AGE
inflate-646745bfb8-29zqz   0/1     Evicted             0          3m55s
inflate-646745bfb8-2zkhb   0/1     Evicted             0          108s
inflate-646745bfb8-8cm7b   0/1     Evicted             0          6m59s
inflate-646745bfb8-d9fwn   0/1     Evicted             0          5m35s
inflate-646745bfb8-dgdfn   0/1     Evicted             0          56s
inflate-646745bfb8-fw9wr   0/1     Evicted             0          5m9s
inflate-646745bfb8-h2gwm   0/1     Evicted             0          48s
inflate-646745bfb8-r5h5k   0/1     Evicted             0          52s
inflate-646745bfb8-trg9t   0/1     Evicted             0          5m31s
inflate-646745bfb8-v99hq   0/1     Evicted             0          2m36s
inflate-646745bfb8-w9klx   0/1     ContainerCreating   0          36s
inflate-646745bfb8-zspwn   0/1     Evicted             0          50s
➜  karpenter git:(outofcpu) ✗ k get nodes
NAME                                            STATUS     ROLES    AGE     VERSION
ip-192-168-130-21.us-west-2.compute.internal    Ready      <none>   6m59s   v1.18.18
ip-192-168-149-251.us-west-2.compute.internal   Ready      <none>   110s    v1.18.18
ip-192-168-15-233.us-west-2.compute.internal    Ready      <none>   19d     v1.18.9-eks-d1db3c
ip-192-168-34-22.us-west-2.compute.internal     Ready      <none>   5m7s    v1.18.18
ip-192-168-41-137.us-west-2.compute.internal    NotReady   <none>   38s     v1.18.18
ip-192-168-45-160.us-west-2.compute.internal    Ready      <none>   2m32s   v1.18.18
ip-192-168-82-151.us-west-2.compute.internal    Ready      <none>   3m55s   v1.18.18
```

```
k get deployment inflate -oyaml | yq e   ".spec" -
progressDeadlineSeconds: 600
replicas: 1
revisionHistoryLimit: 10
selector:
  matchLabels:
    app: inflate
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate
template:
  metadata:
    creationTimestamp: null
    labels:
      app: inflate
  spec:
    containers:
      - image: k8s.gcr.io/pause
        imagePullPolicy: Always
        name: inflate
        resources:
          limits:
            cpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
    dnsPolicy: ClusterFirst
    nodeSelector:
      provisioning.karpenter.sh/name: default
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    terminationGracePeriodSeconds: 30
```
