### ISSUE TITLE
Tolerations don't support defaults or special cases

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#391]
Currently this works
```
      tolerations:
      - effect: NoSchedule
        key: foo
        operator: Equal
        value: bar
```
But this doesn't
```
      tolerations:
      - effect: NoSchedule
        key: foo
        value: bar
```
```
      tolerations:
      - operator: Exists
```
We need to support the full spec at https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
