### ISSUE TITLE
Support extra taints not considered when scheduling Pods

### ISSUE THREAD

**Issue by rustrial** [awslabs/karpenter#628]
**Tell us about your request**

As of today, if taints are defined in [`spec.Constraints.taints`](https://karpenter.sh/docs/reference/#karpenter.sh/v1alpha3.Constraints), the provisioner will not provision nodes for pods that do not have matching tolerations.

> Taints will be applied to every node launched by the Provisioner. If specified, the provisioner will not provision nodes for pods that do not have matching tolerations.

However, some cluster add-ons (usually CNI plugins) use temporary taints on new nodes to make sure no Pods are scheduled onto that nodes unless the CNI `DaemonSet` is ready on that node. Usually, those *temporary node startup taints* are then removed by the `DaemonSet` or by a corresponding controller. A prominent example is [Cilium](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/) which uses the `node.cilium.io/agent-not-ready` taint. 

Adding toleration to all Pods for such *temporary node startup taints* would of course void their purpose and might lead to disfunctional Pods as they are scheduled and started before CNI was properly setup on that node. With its current capabilities karpenter is not powerful enough to support such a setup.

**What do you want us to build?**

Add something like `spec.Constraints.extraTaints`, which contains taints that must be applied to newly created nodes, but might later be removed by workloads and are ignored by the provisioner for scheduling purposes. Specifically, karpenter should support the following behaviour:

- provisioner adds all `extraTaints` to newly created nodes and then forgets about them (does not re-add them if they are later removed by a CNI controller).
- provisioner ignores `extraTaints` when making scheduling decisions

Of course, the proposed solution is just a (viable) placeholder and maybe somebody has a better ideas to resolve this problem, so feel free to propose other solutions.

**Are you currently working around this issue?**

Not using karpenter at all :-(  

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Hey @rustrial, this is a very interesting use case. Thanks for writing it up! We've recently been rethinking the `provisioner.spec.taints` functionality. Specifically, we're thinking about generating taints in response to tolerations, instead of doing nothing. The primary reason for this is to enable use cases where pods wish to run in isolation and would define custom taints to do so. Presently, this would require creating additional provisioners and putting the taints there, which is a bit awkward and high touch.

For your use case, I think the problem is already solved, regardless of our behavior w.r.t taints. This behavior currently works with the AWS VPC CNI and Calico, though I haven't tested Cilium. Let me walk you through the provisioning process:

- User creates a typical workload pod PodA (e.g. pause) from a deployment scale out, etc
- Karpenter sees the pod watch event and begins the provisioning process
- Karpenter computes the resource requirements of daemonsets + PodA and launches a node
- Karpenter immediately creates a node object and binds the pod to the node, before the instance is online
- KCM Node Lifecycle. Contorller taints the node with NotReady: NoExecute/NoSchedule
- KCM Daemonset Lifecycle Controller creates a CNI Pod (cilium/awsvpc/calico/etc) and binds it to the node
- The node connects to the API Server, sees PodA and the CNI Pod, and pulls the images
- PodA does not execute because of the NotReady: NoExecute taint on the node
- CNI Pod does execute because it tolerates NotReady: NoExecute
- CNI Pod does node initialization logic and removes the NotReady taint from the node
- PodA executes because the node no longer has the NoExecute taint

It's a bit complicated, but the key bit is the NoExecute taint created by the NodeLifecycleController. It's designed to be removed by some daemon pod (typically a CNI), which will cause other pods to execute. For any pods that don't rely on the CNI, you can always tolerate this taint.

It's not clear to me why cilium doesn't use this taint, and instead relies on its own `"node.cilium.io/agent-not-ready"`. I'm curious if it already does this. There may be a really good reason for this, in which case, I like your idea about applying taints at provisioning time. I wonder if we could simplify how this is modeled and use the NoExecute semantic. 

```
spec:
  taints:
    - key: node.cilium.io/agent-not-ready
      effect: NoExecute
```

Karpenter will apply this taint to all nodes for this provisioner, but it won't be used in scheduling calculations. I think this is roughly the semantic you want.

**Comment by ellistarn** [comment]
Checking back in. I played with 
```
spec:
  taints:
    - key: node.cilium.io/agent-not-ready
      effect: NoExecute
```
It looks like the podlifecyclecontroller will evict pods immediately if a NoExecute taint exists on the node, so this path isn't going to work. I'm still curious if Cilium supports the node readiness workflow mentioned above.

**Comment by rustrial** [comment]
@ellistarn Thank's for your feedback.

> KCM Node Lifecycle. Contorller taints the node with NotReady: NoExecute/NoSchedule 

Can you please provide some pointers to the documentation of the `NotReady` taint you mentioned. I am not aware of such a taint and would like to read-up on this to figure out whether we can get this working for Cilium. I am only aware of the common taints mentioned in https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-nodes-by-condition and those taints are not treated specially by EKS.

---

> It looks like the podlifecyclecontroller will evict pods immediately if a NoExecute taint exists on the node (unless it tolerates this taint, which by default, they don't), so this path isn't going to work unless we fundamentally change up our binding behavior, which I'm not excited about.

I think I have an idea for a minimal change to the current Binding behaviour and already started to draft a PR, just to figure out whether this might work (at all).

---

> If not, we may need to consider something like readinessTaints as you're suggesting.

I like the term `readinessTaints`, its more descriptive then my placeholder name `provisioningTaints`.

**Comment by ellistarn** [comment]
Heres an example node
```
apiVersion: v1
kind: Node
metadata:
  creationTimestamp: "2021-08-22T16:45:01Z"
  finalizers:
  - karpenter.sh/termination
  labels:
    karpenter.sh/provisioner-name: default
  name: ip-192-168-58-236.us-west-2.compute.internal
spec:
  providerID: aws:///us-west-2d/i-08429eea8403fbe47
  taints:
  - effect: NoSchedule
    key: karpenter.sh/not-ready
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
    timeAdded: "2021-08-22T16:45:01Z"
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    timeAdded: "2021-08-22T16:45:01Z"
status:
  allocatable:
    cpu: "8"
    memory: 30310Mi
    pods: "58"
  conditions:
  - lastHeartbeatTime: "2021-08-22T16:45:01Z"
    lastTransitionTime: "2021-08-22T16:45:01Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: Ready
  - lastHeartbeatTime: "2021-08-22T16:45:01Z"
    lastTransitionTime: "2021-08-22T16:45:01Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: MemoryPressure
  - lastHeartbeatTime: "2021-08-22T16:45:01Z"
    lastTransitionTime: "2021-08-22T16:45:01Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: DiskPressure
  - lastHeartbeatTime: "2021-08-22T16:45:01Z"
    lastTransitionTime: "2021-08-22T16:45:01Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: PIDPressure
```

Until this condition is marked ready, 
```
  - lastHeartbeatTime: "2021-08-22T16:45:01Z"
    lastTransitionTime: "2021-08-22T16:45:01Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: Ready
```
these taints will be applied by the node lifecycle controller 
```
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
    timeAdded: "2021-08-22T16:45:01Z"
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    timeAdded: "2021-08-22T16:45:01Z"
```
See: https://github.com/kubernetes/kubernetes/blob/release-1.17/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L87.

I was trying to find where the cni (or kubelet) sets this condition, but was having a hard time

**Comment by ellistarn** [comment]
>I think I have an idea for a minimal change to the current Binding behaviour and already started to draft a PR, just to figure out whether this might work (at all).
Do you mind sharing the idea? I might be able to help.

**Comment by ellistarn** [comment]
Did a little digging. The kubelet updates the runtime state for the network here:
https://github.com/kubernetes/kubernetes/blob/3a26b864f4e17a6b7e0e673f583a551820a25b36/pkg/kubelet/kubelet.go#L2334.

This then prevents the node status conditions `type: Ready` from becoming true. So CNIs are required to cause this to be true, which will in turn cause the taints to be removed.

**Comment by rustrial** [comment]
@ellistarn I see, your are talking about https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions and specifically about the following two taints, which are set by the "node controller" based on the value of the node's `Ready` condition:

- `node.kubernetes.io/not-ready` (if `Ready == False `)
- `node.kubernetes.io/unreachable` (if `Ready == Unknown`)
- *no taint* (if `Ready == True`)

I also understand that the node's `Ready` condition [depends on](https://github.com/kubernetes/kubernetes/blob/3a26b864f4e17a6b7e0e673f583a551820a25b36/pkg/kubelet/kubelet.go#L2334) the runtime's `NetworkReady` condition. However, I still don't see how a CNI plugin like Cilium could influence (set) the node's `NetworkReady` condition. A [short search](https://github.com/cilium/cilium/search?q=%22NetworkReady%22&type=code) on the Cilium code base reveals no reference to `"NetworkReady"` and the same is true [for AWS CNI plugin](https://github.com/aws/amazon-vpc-cni-k8s/search?q=NetworkReady&type=code). Are we confusing node and pod networking status (conditions) here? A node might have well working and ready networking (e.g. AWS VPC ENI attached ...) while the CNI plugin, which is responsible for pod networking on that node (and not for the node's own networking needs), is not yet ready.

---

> I think I have an idea for a minimal change to the current Binding behaviour and already started to draft a PR, just to figure out whether this might work (at all).

>> Do you mind sharing the idea? I might be able to help.

Sure, as soon as it is ready I will open a `[WIP]` PR.

**Comment by ellistarn** [comment]
Hey @rustrial , I put some comments on the PR. What happens if you simply don't use this taint w/ Cilium? IIUC, it's to prevent a race condition when two CNIs are installed.

**Comment by rustrial** [comment]
@ellistarn Actually, not using the taint we observe that there might occasionally be some Pods which are not properly managed by Cilium, but this could be caused by another race condition in Cilium and is not necessarily related to that taint. I am also curious what conclusion we get from the Slack thread you started on the [Cilium #kubernetes channel](https://cilium.slack.com/archives/C1MATJ5U5/p1629676465103900), hopefully it will shed some light on this.

**Comment by ellistarn** [comment]
> Actually, not using the taint we observe that there might occasionally be some Pods which are not properly managed by Cilium, but this could be caused by another race condition in Cilium and is not necessarily related to that taint.

Do you have any links to this?

**Comment by ellistarn** [comment]
I'd need to dig into this `CriticalAddonsOnly` detail and where it's coming from. What's the problem that you're trying to solve?

**Comment by stevehipwell** [comment]
@ellistarn the docs say that tolerations on workloads will cause taints to be added? This toleration is quite widespread, take a look at the EBS CSI driver chart for example.

**Comment by ellistarn** [comment]
Sorry if I'm being a bit dense, but what's the problem? If there are pending pods that need capacity (ebs csi driver, in this case), Karpenter will generate nodes with taints for those pods. Pods that do not have these tolerations will not be scheduled to these nodes. This ensures that ebs csi driver will only run alongside other workloads that have `CriticalAddonsOnly`

**Comment by stevehipwell** [comment]
@ellistarn the point is that this toleration is to allow scheduling not to drive isolation. It would be undesirable to create a node with this taint for this workload. It's also quite common to tolerate certain taints on workloads that aren't directly targeted at them, these wouldn't want to create the taint either.

**Comment by ellistarn** [comment]
I hear ya. 

>  It would be undesirable to create a node with this taint for this workload.

Can you dig into this a little bit? Why don't you want this pod scheduled?

> It's also quite common to tolerate certain taints on workloads that aren't directly targeted at them, these wouldn't want to create the taint either.

If there is existing capacity without taints, the kube scheduler schedule them without any taint generation. I definitely agree that it's not necessary for karpenter to add the taints for the pod to be scheduled. However, by generating taints, you can ensure isolation via the pod spec, which wouldn't be possible otherwise without creating multiple provisioners.

This creates a tradeoff where nodes are packed less tightly (since pods without those tolerations *could* have been scheduled together).

I could potentially see a pod annotation like `karpenter.sh/generate-taints=true`. What do you think? Do you have any preference for polarity: whether or not it's enabled or disabled by default.

**Comment by stevehipwell** [comment]
@ellistarn sorry for the long response, I've been thinking about this since I first saw Karpenter and compared it to our current solution (see below). The following spec might seem like a big change from your current design but I think it just shifts the configuration into multiple provisioners.

Primary constraints:

- Provisioners are given a priority weight
- Provisioners declare labels, either directly or based on options such as instance type
- Provisioners declare taints
- Provisioners can add additional taints to a node via a custom Karpenter pod annotation

Provisioner selection logic:

- Provisioners are ordered by weight
- First provisioner to have required labels from pod spec and have tolerated taints is selected
- All equally weighted provisioners are evaluated and if suitable added to the first found one
- Potential provisioners are evaluated to pick a winning spec

Traits:

- Can use a single provisioner for simple cases
  - Only need extra provisioners for pooling nodes by type
- Portable pod specifications
  - Can deploy same application in either ASG & CA or Karpenter cluster
  - Tolerations only have impact if desired
- Fully customisable for complex workloads
  - No need to tightly couple spec to specific provisioner with custom annotation

An example use-case would be local SSD storage. Given 3 provisioners:

```yaml
- name: gp
  weight: 50
  instances: [m5]
  labels: []
  taints: []
- name: gp-ssd
  weight: 50
  instances: [m5d]
  labels: [ssd=true]
  taints: []
- name: storage-optimised
  weight: 100
  instances: [i3]
  labels: [storage-optimised=true, ssd=true]
  taints: [storage-optimised]
```

If a general pod is scheduled it might get a m5 or a m5d instance. Then if a pod with a `ssd=true` label selector is scheduled it could go onto an existing `gp-ssd` provisioned node or provision a new one. If the pod tolerates `storage-optimised` it could also be scheduled onto a node from the `storage-optimised` provisioner. If the node had a `storage-optimised=true` selector it could only go onto a node from the `storage-optimised` provisioner.

There needs to be thought given to affinity/anti-affinity rules as this probably need to be retrospective to the scheduler unless you can use a webhook to intercept them before a pod is scheduled. I'm specifically thinking about a multi region soft anti-affinity.

It'd also be great if Karpenter could also add custom labels such as a subnet identifier (there are no default labels suitable for custom networking if you have public and private subnets), presence of SSDs (wouldn't need a custom provisioner for m5d types to select them based on this).

---

For reference our current solution is built as groups of 6 ASGs (an ASG per AZ duplicated between on-demand & spot) created per node pattern, which is based on type (e.g. gp, compute, network, etc), size (large, xlarge, etc) and labels/taints. These ASGs are scaled by Cluster Autoscaler using the priority expander. This pattern get us to about 80% of what we'd like, Karpenter working as I've described above would hit close to 100%.

**Comment by ellistarn** [comment]
Thanks for the writeup. Do you mind porting it to a new issue, since it seems like we're outside of the scope of the original ticket.

**Comment by stevehipwell** [comment]
Thank you for moving this for me @ellistarn I had a busy weekend and didn't get a chance.

**Comment by RetWolf** [comment]
Just wanted to check on the status of this. Another Cilium user here, same problem as the original issue. Currently we work around this by simply restarting all pods on a node when the CNI pod finishes starting up, but this is obviously a hacky workaround we'd like to avoid keeping.

I noticed you specifically mentioned you don't want to complicate the API with new concepts and was just wondering if in the couple months since then if any better ideas had come to mind?

**Comment by ellistarn** [comment]
Is it possible that this could be fixed in the cilium CNI?

**Comment by RetWolf** [comment]
I don't think so. It looks like Cilium uses this taint specifically to block DaemonSets from getting scheduled since they tolerate specific taints - https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations

Do provisioners in Karpenter use different launch templates in AWS? If so, could we expose some way for the user to add custom args to `boostrap.sh ... --kubelet-extra-args`? Karpenter internally could merge the args provided by the user with those that Karpenter already sets. This would allow adding taints or custom labels users might want.

If there's a concern about it being too specific to AWS, the functionality could be exposed purely as a way to pass args to the provisoned nodes kubelet, and the implementation would be left up to the cloud provider

**Comment by ellistarn** [comment]
Users can already add custom taints via `provisioner.taints` which get merged in through kubelet args. This doesn't solve the problem of cilium failing to reconcile pod networking if it's installed after the pods are.

**Comment by RetWolf** [comment]
> Users can already add custom taints via provisioner.taints which get merged in through kubelet args.
Isn't the problem with this that Karpenter uses these taints for scheduling purposes? As in, the pod would have to tolerate these taints for a node to be provisioned. So we can't add the Cilium `not-ready` taint here, as pods would then have to tolerate it, and make the taint a no-op essentially.

> IIUC, the kubelet doesn't even attempt to run the pods until the node is ready, and cilium is responsible for triggering node ready
This might be true, I honestly haven't tested this

**Comment by ellistarn** [comment]
> Isn't the problem with this that Karpenter uses these taints for scheduling purposes? As in, the pod would have to tolerate these taints for a node to be provisioned. So we can't add the Cilium not-ready taint here, as pods would then have to tolerate it, and make the taint a no-op essentially.

D'oh, yes. I lost the thread 🤦 .

**Comment by mKeRix** [comment]
I also stumbled upon this problem when using Cilium (in aws-cni chaining mode) yesterday. As a workaround, I ended up utilizing [Kyverno](https://kyverno.io/) to set the node taint with a mutation policy. I chose to set the taint for all nodes, but in theory you could also write a selector that will only mutate nodes with the `karpenter.sh/provisioner-name` label. My policy looks like this:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-cilium-readiness-taint
spec:
  rules:
  - name: add-cilium-readiness-taint
    match:
      resources:
        kinds:
        - Node
    preconditions:
      any:
      - key: '{{ request.operation }}'
        operator: Equals
        value: CREATE
    mutate:
      patchStrategicMerge:
        spec:
          taints:
          - key: 'node.cilium.io/agent-not-ready'
            value: 'true'
            effect: NoSchedule
```

Maybe this helps someone else, it's working out well for me. :)
