### ISSUE TITLE
Taint not getting removed from node provisioned

### ISSUE THREAD

**Issue by prateekgogia** [awslabs/karpenter#644]
## Version

**Karpenter**: v0.0.0
head on main branch

**Kubernetes**: v1.0.0
v1.19.13-eks-8df270

## Expected Behavior

When a node is provisioned by Karpenter, kube-scheduler should be able to add more pods to the node.

## Actual Behavior

Only the unschedulable pod for which Karpenter provisioned a new node was created, other pods are not scheduled on this node because it has a taint `karpenter.sh/not-ready`

## Steps to Reproduce the Problem

Create 2 pods, one without any affinity and the second one with pod affinity to be scheduled with the first  pod. Second pod never gets created on the node provisioned by Karpenter.

Node was ready 40 minutes ago-

```
 k get node ip-192-168-171-186.us-west-2.compute.internal
NAME                                            STATUS   ROLES    AGE   VERSION
ip-192-168-171-186.us-west-2.compute.internal   Ready    <none>   41m   v1.19.13
```

Taint still exists-
```
k get nodes ip-192-168-171-186.us-west-2.compute.internal -o yaml | grep -i -A 2 taints:
  taints:
  - effect: NoSchedule
    key: karpenter.sh/not-ready
```
Second pod is not scheduled and has this warning -
```
Warning  FailedScheduling  4m35s (x39 over 50m)  default-scheduler  0/5 nodes are available: 1 node(s) had taint {karpenter.sh/not-ready: }, that the pod didn't tolerate, 4 node(s) didn't match node selector.
```
