### ISSUE TITLE
Documentation - helm chart version 0.3.3 crds validation failed

### ISSUE THREAD

**Issue by ksivamuthu** [awslabs/karpenter#697]
## Version

**Karpenter**: v0.3.3

**Kubernetes**: v1.20

## Expected Behavior
1. Installed the karpenter helm chart 0.3.3
2. Add the provisioner with `apiVersion: karpenter.sh/v1alpha4` as in documentation

## Actual Behavior
The helm chart 0.3.3 has `apiVersion: karpenter.sh/v1alpha3`provisioner crd

## Steps to Reproduce the Problem

Follow the steps in this documentation https://karpenter.sh/docs/getting-started/#install-karpenter-helm-chart

Install karpenter chart with version 0.3.3
 ```
 helm upgrade --install karpenter karpenter/karpenter --namespace karpenter \
--create-namespace --set serviceAccount.create=false --version 0.3.3
 ```
Apply the provisioner
   ```
   cat <<EOF | kubectl apply -f -
apiVersion: karpenter.sh/v1alpha4
kind: Provisioner
metadata:
  name: default
spec:
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-${CLUSTER_NAME}
    capacityType: spot
    cluster:
      name: ${CLUSTER_NAME}
      endpoint: $(aws eks describe-cluster --name ${CLUSTER_NAME} --query "cluster.endpoint" --output json)
  ttlSecondsAfterEmpty: 30
EOF
   ```

```
error: unable to recognize "STDIN": no matches for kind "Provisioner" in version "karpenter.sh/v1alpha4"
```
